# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: J:\V BLOG
author:
  name: jeffvaccaro
  email: jeff.vaccaro@gmail.com

description: >
  **Fun Fact:** My 1st job out of college was being QA! My 1st paid app as a developer was to automate my QA job!
  After I was done, I added what amounted to be a read.me:
  **"I'm sorry, but this is my 1st PAID application... You should probably rewrite it!"**

  I'm told that application was around for years before finally being retired!

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.markdown

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic            Default, light color scheme.
  # dark                 Dark variant of the classic skin.
  # auto                 Adaptive skin based on the default classic and dark skins.
  # solarized-light    Light variant of solarized color scheme.
  # solarized-dark     Dark variant of solarized color scheme.
  # solarized            Adaptive skin for solarized color scheme skins.
  skin: dark

  social_links:
  - { platform: github, user_url: "https://github.com/jeffvaccaro" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/jeffvaccaro" }
  - { platform: bluesky, user_url: "https://bsky.app/profile/webdad3.bsky.social" }
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

# Allow future-dated posts to be visible.
future: true

# SASS Configuration
sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .bundle
  - .jekyll-metadata
  - .jekyll-cache
  - .sass-cache

plugins:
  - jekyll-feed
  - jekyll-seo-tag
