# Site settings
title: J:\V BLOG
email: jeff.vaccaro@gmail.com
description: >
  Fun Fact: My 1st job out of college was being QA! My 1st paid app as a developer was to automate my QA job!
  After I was done, I added what amounted to a read.me.. I wrote for that application was something like:
  **"I'm sorry, but this is my 1st real application... Please update it!"**. I think that application lasted for over 5 years!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media settings
github_username: jeffvaccaro
linkedin_username: jeffvaccaro
twitter_username: # Replace with your username or add other social platforms

# Build settings
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include additional files
include:
  - assets/images/
  - assets/css/
